dist: focal
language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
# command to install dependencies
install:
  - pip install requests_mock
  - pip install -e .
# command to run tests
script: nosetests
